### ISSUE TITLE
New version of Topsoil - cannot create Charts

### ISSUE THREAD

**Issue by MarcPoujol** [CIRDLES/Topsoil#220]
I didn't realize that new versions of Topsoil have been released. So I downloaded the latest one (1.0.0. alpha3). No problem to copy the data from Excel and paste them in Topsoil. No problem to save the dataset. But when I select "chart" then "error ellipse chart" nothing happens. same goes with the other chart (scatter plot). Just as I reminder I am running a MacBook Pro with OsX Yosemite and the latest version of Java (Java 8). This Mac is a french one, which caused a few problems in the past...

**Comment by johnzeringue** [comment]
I tried reproducing this issue on my machine (OS X El Capitan, Java 8u60) with `java -jar -Duser.language=fr -Duser.region=FR <path-to-jar>`, but was unable.

@MarcPoujol, can you help us identify your exact Java version? Open the Terminal application, type `java -version`, and press enter. You can copy the whole output here.

Thanks for being so eager to try new versions of Topsoil. Your bug reports are making a huge difference for international users.

**Comment by MarcPoujol** [comment]
Le 18/10/2015 23:22, John Zeringue a écrit :
>
> I tried reproducing this issue on my machine (OS X El Capitan, Java 
> 8u60) with |java -jar -Duser.language=fr -Duser.region=FR 
> <path-to-jar>|, but was unable.
>
> @MarcPoujol <https://github.com/MarcPoujol>, can you help us identify 
> your exact Java version? Open the Terminal application, type |java 
> -version|, and press enter. You can copy the whole output here.
>
> Thanks for being so eager to try new versions of Topsoil. Your bug 
> reports are making a huge difference for international users.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/CIRDLES/Topsoil/issues/220#issuecomment-149048370>.
>
Hi John,

here is what I got :

java version "1.8.0_20"
Java(TM) SE Runtime Environment (build 1.8.0_20-b26)
Java HotSpot(TM) 64-Bit Server VM (build 25.20-b23, mixed mode)

Marc

--

**Comment by johnzeringue** [comment]
I think the issue is that you don't have the latest Java update. Are you able to upgrade? The newer releases are now only compatible with Java 8u40 and up.

**Comment by MarcPoujol** [comment]
Le 19/10/2015 17:40, John Zeringue a écrit :
> I think the issue is that you don't have the latest Java update. Are 
> you able to upgrade? The newer releases are now only compatible with 
> Java 8u40 and up. 
John

The problem is that if I install the latest version of Java (which I did 
yesterday when installing OS X El Capitan), some of my softwares don't 
work any more (such as Adobe Illustrator CS6)... Apple then asked me to 
download an older version of Java so that Illustrator could work.

So I guess that if everybody needs the latest version of Java every time 
you release a new version of Topsoil, a lot of people might encounter 
then same problem ... This was already an issue with Isoplot as newer 
version of Excel were not compatible any more with the latest version of 
Isoplot.

There is no way that you can make a version of Topsoil that does not 
require to update Java every so often?
Thank you for your help
Marc


--

**Comment by johnzeringue** [comment]
Thanks for the feedback. I was curious if updating Java like this was going to be an issue for some. I can assure you that we won't require newer than Java 8u40 for a while, and won't ever need newer than Java 8. I think I'm still able to make it work again for Java 8u20, though. I'll get back to you later today.

**Comment by johnzeringue** [comment]
Actually, I was mistaken about the current build of Topsoil requiring Java 8u40. I was able to successfully run it on my laptop using Java 8u20 with and without the language options I gave above.

Give me a couple of days to add some new logging features to Topsoil, and I'll try to debug your issues then. I'm not sure exactly what's still wrong, but I've got some ideas (mostly related to the new storage system), and I don't want to overwhelm you with the debugging process.

**Comment by johnzeringue** [comment]
In the meantime, if you have a spare minute, you can run `curl -LO https://github.com/CIRDLES/Topsoil/releases/download/v1.0.0-alpha.3/topsoil-v1.0.0-alpha.3.jar && java -jar topsoil-v1.0.0-alpha.3.jar` (all one command like `java -version`) and provide the output just in case I'm not as clever as I think I am.

**Comment by johnzeringue** [comment]
@MarcPoujol, thanks for your patience. Today I released a fix for a bug that I believe may have caused your problem. The version with the fix is `1.0.0-alpha.4`.

If this release does not work, try running `curl -LO https://github.com/CIRDLES/Topsoil/releases/download/v1.0.0-alpha.4/topsoil-v1.0.0-alpha.4.jar && java -jar topsoil-v1.0.0-alpha.4.jar` in Terminal, reproduce the issue, and paste the output here.

**Comment by MarcPoujol** [comment]
Le 26/10/2015 19:48, John Zeringue a écrit :
>
> @MarcPoujol <https://github.com/MarcPoujol>, thanks for your patience. 
> Today I released a fix for a bug that I believe may have caused your 
> problem. The version with the fix is |1.0.0-alpha.4|.
>
> If this release does not work, try running |curl -LO 
> https://github.com/CIRDLES/Topsoil/releases/download/v1.0.0-alpha.4/topsoil-v1.0.0-alpha.4.jar 
> && java -jar topsoil-v1.0.0-alpha.4.jar| in Terminal, reproduce the 
> issue, and paste the output here.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/CIRDLES/Topsoil/issues/220#issuecomment-151245637>.
>
Hi John

Sorry I was busy the past few days. So now it works. But I have a few 
concerns:

- First I can't find how to create Tera Wasserburg diagrams anymore.
- The Fit data button doesn't work (ie if I click nothing happens)
- there is a scary difference between Topsoil and Isoplot when I plot 
data (see two attached files). It is obvious that the ellipses do not 
plot at the same place...
- When Topsoil plots the ellipses, does it plot them at 1 sigma or at 2 
sigma?
- I thing that the new graphic interface is not as versatile as the old 
one was. For example it is very hard to zoom in and out. And impossible 
to fix the min and max for X and Y with those cursors.

Sorry to be so critical,

Thank you again for all your efforts,
Kind regards

Marc


--

**Comment by johnzeringue** [comment]
Thanks for verifying that this bug was fixed.

The new version is a complete rewrite of the older version of Topsoil. In the long term, it will allow us to create more flexible visualizations. In the meantime, there might be some regressions from 0.4.2. We're working to add these back as quickly as possible.

To address your concerns point by point:

> - First I can't find how to create Tera Wasserburg diagrams anymore.

The Tera-Wasserburg concordia hasn't been reimplemented yet. You can track the progress of this feature at #226.

> - The Fit data button doesn't work (ie if I click nothing happens)

I've yet to observe an issue with the "Fit data" button. I'll investigate further later this week, using your version of the JRE and language settings.

> - there is a scary difference between Topsoil and Isoplot when I plot
> data (see two attached files). It is obvious that the ellipses do not
> plot at the same place...

File attachments do not come through GitHub email. I'm interested in seeing the images, but you need to post them through the GitHub interface.

> - When Topsoil plots the ellipses, does it plot them at 1 sigma or at 2
> sigma?

Topsoil is current only plotting at 1σ. Of course, this will be added back soon. You can track that progress at #227.

> - I thing that the new graphic interface is not as versatile as the old
> one was. For example it is very hard to zoom in and out. And impossible
> to fix the min and max for X and Y with those cursors.

I agree. We'll be working on this over the next few releases (which will become more frequent).

> Sorry to be so critical,

Don't be! We've got thick skin! Documenting problems and shortcomings is important to the project. 

We're know we've taken a few steps backwards, but please don't be dismayed. We fixed a lot of internal issues that will (and already do) allow us to improve upon the first Topsoil. This will be the last rewrite, and we should have everything added back soon.

Thanks for your help!
