### ISSUE TITLE
Add uncertainty ellipse size configuration to v1

### ISSUE THREAD

**Issue by johnzeringue** [CIRDLES/Topsoil#227]
In the latest versions of Topsoil (the v1 alphas), it is no longer possible to configure the size of the uncertainty ellipses, because that functionality has yet to be reimplemented. At the moment, all uncertainty ellipses plot as 1σ ellipses. @noahmclean has provided [an excellent explanation of what this means](https://github.com/CIRDLES/Topsoil/issues/120).

---

November 2nd

Updated based on comment below.

**Comment by noahmclean** [comment]
Before the wrong nomenclature propagates too far... these aren't 'error ellipses', despite the nice alliteration, they are uncertainty ellipses.  The distinction between 'error' and 'uncertainty' is both important and useful in metrology -- the modern science of measurement, a branch of statistics.  

**Short Story:** 
An **error** is the difference between the measured value and the true value. For instance, check out the paper here: http://www.mantleplumes.org/WebDocuments/Renne1997.pdf .  In it, 1,918 years after the 79 AD eruption of Vesuvius (in 1997), pumice from that eruption was dated to be 1,925 years old.  The error here therefore 7 years.  Note that this is a special case -- we usually don't have human records for the events that we're dating, like the extinction of the dinosaurs 66 million years ago!  
An **uncertainty** is the range of values (usually stated with a ± ) that could reasonably be assigned to that age, with an estimated probability that the true value lies in this range (often part of a measured or assumed probability distribution, e.g. Gaussian).  In the Vesuvius paper, the uncertainty is ± 94 years, so that the date is reported as 1925 ± 94 years ago.  Rather importantly, there's no hint in that paper whether this is a 1σ or 2σ (68% or 95%) uncertainty -- it is probably 1σ, as this is the convention for Ar-Ar dates (but not for any other system, who prefer 95% confidence intervals).

**Long Story:**
The VIM, or international vocabulary of metrology, is the go-to glossary for definitions, though sometimes the English writing there can be a bit muddled.  Go to http://jcgm.bipm.org/vim/en/ and navigate to 2.16 for the definition of 'measurement error' and to 2.26 for 'measurement uncertainty'.  I think this is a useful distinction, though I don't really find the way they distinguish accuracy, precision, and trueness to be very helpful.

**Comment by johnzeringue** [comment]
Thanks for the explanation and the reference. I'll try to be better about this.

@bowring, what you so lovingly call "value models" are apparently "measurement results".

**Comment by bowring** [comment]
thanks.  valueModel is an abstraction to model any named quantity and its
associated uncertainties, whether measured, calculated, or estimated.

On Mon, Nov 2, 2015 at 9:01 PM, John Zeringue <notifications@github.com>
wrote:

> Thanks for the explanation and the reference. I'll try to be better about
> this.
>
> @bowring <https://github.com/bowring>, what you so lovingly call "value
> models" are apparently "measurement results".
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CIRDLES/Topsoil/issues/227#issuecomment-153216653>.
>



-- 
Jim Bowring
C. Richard Crosby Distinguished Teaching Co-Chair
Principal Investigator, www.CIRDLES.org, www.github.com/cirdles

Computer Science
College of Charleston
66 George Street
Charleston, SC 29424

Google Voice: 843.608.1399 (preferred)
Google Email: bowring@gmail.com

Office:
Harbor Walk East (360 Concord Street) Room 308
843.953.0805
http://stono.cs.cofc.edu/~bowring/
bowringj@cofc.edu

R. Buckminster Fuller (1972):
If humanity is to survive aboard our planet, it must become universally
literate and preoccupied with inherently cooperative Comprehensive
Anticipatory Design Science in which every human is concerned with
accomplishing the comfortably sustainable well-faring of all other humans.

**Comment by johnzeringue** [comment]
This is fixed in #236.
