### ISSUE TITLE
TOPSOIL unresponsive when plotting ellipses from an assumed CSV file

### ISSUE THREAD

**Issue by Felipe-UnB** [CIRDLES/Topsoil#246]
I was trying to export my data to a CSV format, but excel used ";" in opposite to ",". The result was that TOPSOIL was not able to break the data into the correct columns. Nevertheless, I tried going to Charts>uncertainty elipse charts. It was just a test to see how the program would deal with my data. Well, it didn't actually crash, but it became unresponsive and started to use something like 30% of my processor time.
![topsoil csv issue](https://cloud.githubusercontent.com/assets/8608912/11349320/c799a090-9212-11e5-86f0-40266a820549.jpg)
 
The file that I was testing is:
[Resultados 91500 - TOPSOIL issue.txt](https://github.com/CIRDLES/Topsoil/files/42021/Resultados.91500.-.TOPSOIL.issue.txt)

I know that it is that kind of impossible situation, when the user knows the data format is not correct, but I am reporting because it might be just the case to add a simple error handling.

**Comment by johnzeringue** [comment]
Yeah, we weren’t expecting datasets quite so big (since they aren’t well-suited to error-ellipses), so we were finding that your data rendered very slowly too. Maybe we’ll add a scatterplot with a Wetherill curve.

I’ve had some thoughts about detecting bad data, but that’s too large of a project for the moment. Thanks for the feedback, though! It’ll come eventually!

Best,
John
