### ISSUE TITLE
Problem exporting to PDF and SVG

### ISSUE THREAD

**Issue by ryanickert** [CIRDLES/Topsoil#442]
I'm having problems exporting plots as SVG or PDF on my Windows 10 PC.  Saving as a PDF  yields a file of size zero that can't be opened.  Saving as an SVG yields a file that can be opened in Explorer (!) or Inkscape, but will crash Adobe Illustrator CS6.  Opening in Inkscape and trying to save as PDF also doesn't work, but I can open in Inkscape and save as a plain SVG, then open resulting file in illustrator.  The example data that I used are in the attached csv file (X, sX, y, sY, rho; 2sigma absolute) but it doesn't seem to be dataset specific.

[testdata_v1.txt](https://github.com/CIRDLES/Topsoil/files/3064252/testdata_v1.txt)

Topsoil Version: v3.0.0-alpha-1-g7e2ed7e
Java Version: 1.8.0_65
Operating System: Windows 10 10.0
***

**Comment by marottajb** [comment]
It seems that the problem is that Topsoil isn't properly handling rho values less than 0 or greater than 1.  Row 2 of the data has a rho value of 1.034383836, so the ellipse for that row isn't being calculated correctly, leading to an incorrect SVG file. Consequently, the transcoder we use to convert the SVG file to a PDF file can't read it. I'll add a change that filters rows for their row values.

**Comment by bowring** [comment]
rho must be [-1,...,1] otherwise convert it to a zero and alert user

**Comment by ryanickert** [comment]
Ugh, that's embarrassing.  I don't know how I missed it.  (The sample with a rho set to zero is also a value >1; they are back calculated from literature values and some of the quantities have been reported incorrectly).  I should have seen it and flagged it as the culprit.  Thanks folks!

**Comment by marottajb** [comment]
Invalid rho values are highlighted as of #443
